package editorDeTextoGUI;

public enum NuiCommand {
	ABRIR_DOCUMENTO, GUARDAR_DOCUMENTO, APLICAR_NEGRITA, APLICAR_CURSIVA, CAMBIAR_COLOR, INVERTIR, MAYUSCULAS,
	MINUSCULAS, BUSCAR_REEMPLAZAR, ELIMINAR_ESPACIOS
}
